//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCBoardBridge.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IRCBoardBridge.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die by ähnelt.
        /// </summary>
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;Bot&gt; changed nickname to {0} ähnelt.
        /// </summary>
        internal static string MessageBotChangedNickname {
            get {
                return ResourceManager.GetString("MessageBotChangedNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;Bot&gt; joined channel {0} ähnelt.
        /// </summary>
        internal static string MessageBotJoinedChannel {
            get {
                return ResourceManager.GetString("MessageBotJoinedChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;Bot&gt; left channel {0} ähnelt.
        /// </summary>
        internal static string MessageBotLeftChannel {
            get {
                return ResourceManager.GetString("MessageBotLeftChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Host: {0} ähnelt.
        /// </summary>
        internal static string MessageDebugPrintHost {
            get {
                return ResourceManager.GetString("MessageDebugPrintHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Port: {0} ähnelt.
        /// </summary>
        internal static string MessageDebugPrintPort {
            get {
                return ResourceManager.GetString("MessageDebugPrintPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SSL: {0} ähnelt.
        /// </summary>
        internal static string MessageDebugPrintSSL {
            get {
                return ResourceManager.GetString("MessageDebugPrintSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error: {0} ähnelt.
        /// </summary>
        internal static string MessageErrorOccurred {
            get {
                return ResourceManager.GetString("MessageErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connecting to IRC network... ähnelt.
        /// </summary>
        internal static string MessageIRCConnecting {
            get {
                return ResourceManager.GetString("MessageIRCConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IRC connection succeeded. ähnelt.
        /// </summary>
        internal static string MessageIRCConnectionSuccess {
            get {
                return ResourceManager.GetString("MessageIRCConnectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IRC disconnected. ähnelt.
        /// </summary>
        internal static string MessageIRCDisconnected {
            get {
                return ResourceManager.GetString("MessageIRCDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IRC session state changed to {0} ähnelt.
        /// </summary>
        internal static string MessageIRCSessionStateChanged {
            get {
                return ResourceManager.GetString("MessageIRCSessionStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {1} changed nickname to {0} ähnelt.
        /// </summary>
        internal static string MessageIRCUserChangedNickname {
            get {
                return ResourceManager.GetString("MessageIRCUserChangedNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {1} joined channel {0} ähnelt.
        /// </summary>
        internal static string MessageIRCUserJoinedChannel {
            get {
                return ResourceManager.GetString("MessageIRCUserJoinedChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {1} left channel {0} ähnelt.
        /// </summary>
        internal static string MessageIRCUserLeftChanne {
            get {
                return ResourceManager.GetString("MessageIRCUserLeftChanne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Watcher running. ähnelt.
        /// </summary>
        internal static string MessageWatcherRunning {
            get {
                return ResourceManager.GetString("MessageWatcherRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New post ähnelt.
        /// </summary>
        internal static string NewPost {
            get {
                return ResourceManager.GetString("NewPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New thread ähnelt.
        /// </summary>
        internal static string NewThread {
            get {
                return ResourceManager.GetString("NewThread", resourceCulture);
            }
        }
    }
}
